### PR TITLE
better QR code UI/UX via add install client path url from wireguard site as first comment in client conf file

### PR DESCRIPTION
**Pull request by iqdoctor**
# https://www.wireguard.com/install
it make QR code scanning process clever even in default photo app on my phone

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
What is this PR?

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/d0081d8bb0a2602152ab4e7c6ff6226e93308609

**Comment by iqdoctor** [comment]
> U changed the update url from this repo to your repo, Why?
sorry it my mistake, I use my repo to deliver my charges 

also I see that you replace http://wireguard.com/install/ to http://wireguard.com

I prefer http://wireguard.com/install because it directly points out to clients to all platforms  

Then client first time see new QR code and do no understand that is is link to install page is best solution

**Comment by iqdoctor** [comment]
PR := pull request

**Comment by Prajwal-Koirala** [comment]
> > U changed the update url from this repo to your repo, Why?
> 
> sorry it is my mistake, I use my repo to deliver my charges to my servers. not for PR to main repo - it is mistake.
> 
> also I see that you replace http://wireguard.com/install/ to http://wireguard.com
> 
> I prefer http://wireguard.com/install because it directly points out to clients to all platforms
> 
> Then client first time see new QR code and do no understand that is is link to install page is best solution

I understand that but if ur giving it to a client who doesn't understand what the config is for than i feel like the main website is better, its very simple to find the install page from the website itself.

**Comment by iqdoctor** [comment]
I can make my repo private if you want

**Comment by Prajwal-Koirala** [comment]
> I can make my repo private if you want

No, God NO.

**Pull request closed without merging**
