### PR TITLE
Create LICENSE

### LINKED ISSUE #44: License?
Please consider adding a license to this software. Thanks!
https://choosealicense.com/

### PR DESCRIPTION
**Pull request by garritfra**
Fixes #44

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
This is inside `.github/` folder

**Comment by garritfra** [comment]
But why?

**Comment by Prajwal-Koirala** [comment]
The repo will be much cleaner if its in `.github/` folder, don't worry this project is under MIT, People will never have to worry anything legally about this.

**Comment by Prajwal-Koirala** [comment]
@garritfra 
The LICENSE was changed from MIT to Unlicensed to give the users more freedom.
I am being honest, do whatever i don't really care nor do i enforce anything like this.

If u have free time and want to contribute to the project please feel free.

**Pull request closed without merging**
