### PR TITLE
Optimizing the code and working on current features instead of trying to add new ones.

### PR DESCRIPTION
**Pull request by Prajwal-Koirala**

### CODE REVIEW

**Comment by Saugjunkie** [comment]
Why you go from /64 to /08?

**Comment by Prajwal-Koirala** [comment]
```
# 10.0.0.0/8 fd00:00:00::0/8 45.63.0.213:51820 l4EndI6tgV+mG6VMgdBTUzVth/38F2DylORknQuWtwE= 10.0.0.1,fd00:00:00:1 1280 25 0.0.0.0/0,::/0
#
[Interface]
Address = 10.0.0.1/8,fd00:00:00::1/8
ListenPort = 51820
MTU = 1280
PrivateKey = MCQLf0bdwnPIBY0iaAQye2jCIyHjLmoRZQWCECV+P2Q=
SaveConfig = false
# f76b4f991fe1c17ec7db61ef887edb415c0849ce5a5e7f3818 start
[Peer]
PublicKey = 0PstGV/MGjxr6XKmRvU/RofWbCGxKU/pRITBp26KVAM=
PresharedKey = I+TR3PbZ/qaT/Rv6s4lgU3pB2nH/DSkX0S26CQGd+yU=
AllowedIPs = 10.0.0.3/32,fd00:00:00::3/128
# f76b4f991fe1c17ec7db61ef887edb415c0849ce5a5e7f3818 end
# cebe87f01fc9a462082399cbcd6315bfb12f98dbe650c3d987 start
[Peer]
PublicKey = rMLFaj0lznGwsitj4599qmcxDlkzJrFGBipIFftwiG8=
PresharedKey = 7IDgJK2ighQzt0KYnqRnwhWufpKqV+52Uoop4ET7gaE=
AllowedIPs = 10.0.0.4/32,fd00:00:00::4/128
# cebe87f01fc9a462082399cbcd6315bfb12f98dbe650c3d987 end
```

**Comment by Prajwal-Koirala** [comment]
> Why you go from /64 to /08?

Unlimited clients.

**Comment by Prajwal-Koirala** [comment]
Max clients for `/24` is 254.
Max clients for `/8` is 16777214.

**Comment by Prajwal-Koirala** [comment]
Screenshot_20210908-104424
Works

**Comment by Prajwal-Koirala** [comment]
### Note: When its 255 clients go to the next range.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/201

**Pull request closed without merging**
