### PR TITLE
openresolv error on redhad based OS.

### PR DESCRIPTION
**Pull request by Prajwal-Koirala**
https://github.com/complexorganizations/wireguard-manager/issues/258

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
This isn't completed and still needs to add a check to install the correct source and than install it and than remove it.

**Comment by Rebelllious** [comment]
I managed to do my implementation of openresolv installation for the rhel family and was about to submit a pull request, but testing showed the issue with DNS resolution on CentOS (and presumably the whole rhel family) gets broken at some point during the script run and is not resolved by proper installation of unbound/openresolv. I will continue debugging it, as several things get broken there.
You can wait with this one until then.

**Comment by Rebelllious** [comment]
I have been able to perform a successful installation using my modification of the script (including unbound and openresolv). It has quite a few modifications, so I will prepare my pull request soon. Prior to that, I would need to test it on all current RHEL family distributions, as at the moment it looks like it's only tested on Ubuntu/Debian exclusively.

**Comment by Prajwal-Koirala** [comment]
> I have been able to perform a successful installation using my modification of the script (including unbound and openresolv). It has quite a few modifications, so I will prepare my pull request soon. Prior to that, I would need to test it on all current RHEL family distributions, as at the moment it looks like it's only tested on Ubuntu/Debian exclusively.

okay sounds good.

**Comment by Rebelllious** [comment]
As part of this testing I discovered #271 - it's been producing consistent error 502 for several days already. I would suggest reconsidering having this source as part of the script - just for the sake of avoiding random failures.

**Comment by Prajwal-Koirala** [comment]
> As part of this testing I discovered #271 - it's been producing consistent error 502 for several days already. I would suggest reconsidering having this source as part of the script - just for the sake of avoiding random failures.

Done.

**Pull request closed without merging**
