### PR TITLE
Fix for incorrect kernel version detection

### PR DESCRIPTION
**Pull request by Rebelllious**
This fix is confirmed to eliminate issue #256 with incorrect kernel version detection, where kernel 3.10 was considered in need of an upgrade, whereas 3.1 was the minimum supported version.
Tested on CentOS 7.

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
I will test this in a bit but if the code works, I will give u a french kiss.
Jokes.

**Comment by Prajwal-Koirala** [comment]
```
root@Prajwal-Desktop:/mnt/c/Users/prajw# bash test.sh
(standard_in) 1: syntax error
```

**Comment by Rebelllious** [comment]
What OS (distribution and version, please) did you test this with? I would like to recheck it on my side in the same environment.
I am a bit surprised that you got an error as before submitting the pull request I did test it on CentOS 7.9 and it worked just fine for me.

**Comment by Prajwal-Koirala** [comment]
> What OS (distribution and version, please) did you test this with? I would like to recheck it on my side in the same environment. I am a bit surprised that you got an error as before submitting the pull request I did test it on CentOS 7.9 and it worked just fine for me.

Debian WSL

**Comment by Prajwal-Koirala** [comment]
```
#!/usr/bin/env bash

# Lets check the kernel version
function kernel-check() {
  CURRENT_KERNEL_VERSION="3.10.0-1160.el7.x86_64"
  ALLOWED_KERNEL_VERSION="3.1"
  if (($(echo '"$CURRENT_KERNEL_VERSION" <= "$ALLOWED_KERNEL_VERSION"' | bc -l))); then
    echo "Error: Kernel ${CURRENT_KERNEL_VERSION} not supported, please update to ${ALLOWED_KERNEL_VERSION}."
    exit
  fi
}

kernel-check
```

**Comment by Rebelllious** [comment]
I confirmed I screwed it up at some testing point. I will redo things.
Yet, I've checked the current implementation from the main on the latest Ubuntu Server LTS and it fails the same way as it failed on CentOS 7.
Will look into this additionally.

**Comment by Rebelllious** [comment]
Feel free to close this pull request with no further action, I will submit a new one once I get everything sorted out and tested.

**Pull request closed without merging**
