### PR TITLE
Add support for "neon" (KDE neon)

### PR DESCRIPTION
**Pull request by brianw21**
Added "neon" (KDE neon) to the list of compatible ubuntu derivatives.

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
Hey,
I got a question.

Can i change your code?

Also do u have a website for their OS or somewhere i can get more info on them.

**Comment by Prajwal-Koirala** [comment]
```
Note: 
- Add support for uninstall
- Install a VM of this OS and than test it.
- Complete more checks on this since the code is untested and just used the github web editor to edit the code.
```

**Comment by Prajwal-Koirala** [comment]
```
Note: 
- Install a VM of this OS and than test it.
- Complete more checks on this since the code is untested and just used the github web editor to edit the code.
```

**Comment by Prajwal-Koirala** [comment]
https://neon.kde.org/

**Comment by brianw21** [comment]
Go ahead and make any changes.👍. The website is neon.kde.org

**Comment by Prajwal-Koirala** [comment]
Can u please more changes to this PR, i am very new to this disto so i need a bit more time to test it and fix any issues.

**Comment by Prajwal-Koirala** [comment]
Tested it and it works fine.

**Pull request merged**
