### PR TITLE
Oracle Linux Support

### PR DESCRIPTION
**Pull request by Prajwal-Koirala**

### CODE REVIEW

**Comment by LM1LC3N7** [comment]
Hello

Sorry for the delay. Here my test (FR):

```bash
# bash wireguard-manager.sh
Dernière vérification de l’expiration des métadonnées effectuée il y a 1:37:09 le mar. 03 août 2021 09:51:34 CEST.
Dépendances résolues.
Rien à faire.
Terminé !
Dernière vérification de l’expiration des métadonnées effectuée il y a 1:37:12 le mar. 03 août 2021 09:51:34 CEST.
Le paquet iptables-1.8.4-17.0.1.el8.x86_64 est déjà installé.
Le paquet curl-7.61.1-18.el8.x86_64 est déjà installé.
Le paquet coreutils-8.30-8.0.1.el8.x86_64 est déjà installé.
Le paquet sed-4.5-2.el8.x86_64 est déjà installé.
Le paquet e2fsprogs-1.45.6-1.el8.x86_64 est déjà installé.
Le paquet zip-3.0-23.el8.x86_64 est déjà installé.
Le paquet unzip-6.0-45.el8_4.x86_64 est déjà installé.
Le paquet grep-3.1-6.el8.x86_64 est déjà installé.
Le paquet gawk-4.2.1-2.el8.x86_64 est déjà installé.
Le paquet systemd-239-45.0.2.el8_4.2.x86_64 est déjà installé.
Le paquet openssl-1:1.1.1g-15.el8_3.x86_64 est déjà installé.
Aucune correspondance pour le paramètre: cron
Aucune correspondance pour le paramètre: ntp
Le paquet lsof-4.93.2-1.el8.x86_64 est déjà installé.
Erreur : Impossible de trouver une correspondance: cron ntp
wireguard-manager.sh: ligne 90: bc : commande introuvable
Error: Kernel 5.4 not supported, please update to 3.1
```

So multiple errors:

1. Tries to install `cron ntp` which seems not to exist: `Erreur : Impossible de trouver une correspondance: cron ntp` (cannot find cron and ntp)
2. Does not install `bc`. You should add `dnf install bc -y` before line 90.
3. Kernel is detected as not up to date but 5.4 > 3.1. `Error: Kernel 5.4 not supported, please update to 3.1`. Orale Linux uses Unbreakable Enterprise Kernel.

Once I installed manually `bc` the installation continue and ask what should be installed (Interface or Peer).

**Comment by LM1LC3N7** [comment]
Also at the end of the installation there is another error related to `cron`:

```bash
Failed to enable unit: Unit file cron.service does not exist.
Failed to start cron.service: Unit cron.service not found.
```

**Comment by Prajwal-Koirala** [comment]
Changes are welcome, I will try and fix it by the end of the day.

**Comment by LM1LC3N7** [comment]
Finally when I create a new client, there are errors regarding `ntpq` and `cron` again

```bash
Let's name the WireGuard Peer. Use one word only, no special characters, no spaces.
Client name: OP7
Dernière vérification de l’expiration des métadonnées effectuée il y a 2:01:48 le mar. 03 août 2021 09:51:34 CEST.
Dépendances résolues.
Rien à faire.
Terminé !
Dernière vérification de l’expiration des métadonnées effectuée il y a 2:01:51 le mar. 03 août 2021 09:51:34 CEST.
Aucune correspondance pour le paramètre: kernel-headers-5.4.17-2102.200.13.el8uek.x86_64
Aucune correspondance pour le paramètre: kernel-devel-5.4.17-2102.200.13.el8uek.x86_64
Erreur : Impossible de trouver une correspondance: kernel-headers-5.4.17-2102.200.13.el8uek.x86_64 kernel-devel-5.4.17-2102.200.13.el8uek.x86_64
2543
Removed /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service.
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service → /usr/lib/systemd/system/wg-quick@.service.
Failed to reenable unit: Unit file ntp.service does not exist.
Failed to restart ntp.service: Unit ntp.service not found.
wireguard-manager.sh: ligne 1224: ntpq : commande introuvable
```

**Comment by LM1LC3N7** [comment]
Is it normal behaviour to update all dependencies when a command is executed?

```bash
# bash wireguard-manager.sh --list
Dernière vérification de l’expiration des métadonnées effectuée il y a 2:12:29 le mar. 03 août 2021 09:51:34 CEST.
Dépendances résolues.
Rien à faire.
Terminé !
Dernière vérification de l’expiration des métadonnées effectuée il y a 2:12:32 le mar. 03 août 2021 09:51:34 CEST.
Le paquet iptables-1.8.4-17.0.1.el8.x86_64 est déjà installé.
Le paquet curl-7.61.1-18.el8.x86_64 est déjà installé.
Le paquet coreutils-8.30-8.0.1.el8.x86_64 est déjà installé.
Le paquet bc-1.07.1-5.el8.x86_64 est déjà installé.
Le paquet jq-1.5-12.el8.x86_64 est déjà installé.
Le paquet sed-4.5-2.el8.x86_64 est déjà installé.
Le paquet e2fsprogs-1.45.6-1.el8.x86_64 est déjà installé.
Le paquet zip-3.0-23.el8.x86_64 est déjà installé.
Le paquet unzip-6.0-45.el8_4.x86_64 est déjà installé.
Le paquet grep-3.1-6.el8.x86_64 est déjà installé.
Le paquet gawk-4.2.1-2.el8.x86_64 est déjà installé.
Le paquet systemd-239-45.0.2.el8_4.2.x86_64 est déjà installé.
Le paquet openssl-1:1.1.1g-15.el8_3.x86_64 est déjà installé.
Aucune correspondance pour le paramètre: cron
Aucune correspondance pour le paramètre: ntp
Le paquet lsof-4.93.2-1.el8.x86_64 est déjà installé.
Erreur : Impossible de trouver une correspondance: cron ntp
What do you want to do?
   1) Show WireGuard
   2) Start WireGuard
   3) Stop WireGuard
   4) Restart WireGuard
   5) Add WireGuard Peer (client)
   6) Remove WireGuard Peer (client)
   7) Reinstall WireGuard
   8) Uninstall WireGuard
   9) Update this script
   10) Backup WireGuard
   11) Restore WireGuard
   12) Check WireGuard Status
interface: wg0
  public key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
  private key: (hidden)
  listening port: 51820

peer: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
  preshared key: (hidden)
  allowed ips: xxxxxx/32, xxxxxxxx/128

```

**Comment by LM1LC3N7** [comment]
At the end, there is multiple errors but the Wireguard server is working. I was able to connect using my phone 😃 

When I try to backup:

```bash
# bash wireguard-manager.sh --backup
Dernière vérification de l’expiration des métadonnées effectuée il y a 2:15:40 le mar. 03 août 2021 09:51:34 CEST.
Dépendances résolues.
Rien à faire.
Terminé !
Dernière vérification de l’expiration des métadonnées effectuée il y a 2:15:43 le mar. 03 août 2021 09:51:34 CEST.
Le paquet iptables-1.8.4-17.0.1.el8.x86_64 est déjà installé.
Le paquet curl-7.61.1-18.el8.x86_64 est déjà installé.
Le paquet coreutils-8.30-8.0.1.el8.x86_64 est déjà installé.
Le paquet bc-1.07.1-5.el8.x86_64 est déjà installé.
Le paquet jq-1.5-12.el8.x86_64 est déjà installé.
Le paquet sed-4.5-2.el8.x86_64 est déjà installé.
Le paquet e2fsprogs-1.45.6-1.el8.x86_64 est déjà installé.
Le paquet zip-3.0-23.el8.x86_64 est déjà installé.
Le paquet unzip-6.0-45.el8_4.x86_64 est déjà installé.
Le paquet grep-3.1-6.el8.x86_64 est déjà installé.
Le paquet gawk-4.2.1-2.el8.x86_64 est déjà installé.
Le paquet systemd-239-45.0.2.el8_4.2.x86_64 est déjà installé.
Le paquet openssl-1:1.1.1g-15.el8_3.x86_64 est déjà installé.
Aucune correspondance pour le paramètre: cron
Aucune correspondance pour le paramètre: ntp
Le paquet lsof-4.93.2-1.el8.x86_64 est déjà installé.
Erreur : Impossible de trouver une correspondance: cron ntp
What do you want to do?
   1) Show WireGuard
   2) Start WireGuard
   3) Stop WireGuard
   4) Restart WireGuard
   5) Add WireGuard Peer (client)
   6) Remove WireGuard Peer (client)
   7) Reinstall WireGuard
   8) Uninstall WireGuard
   9) Update this script
   10) Backup WireGuard
   11) Restore WireGuard
   12) Check WireGuard Status
        zip warning: name not matched: /etc/wireguard/wireguard-peer
zip I/O error: No such file or directory
zip error: Could not create output file (/var/backups/wireguard-manager.zip)

```

**Pull request closed without merging**
