### PR TITLE
Fix for resolvconf in RHEL based distros

### PR DESCRIPTION
**Pull request by Rebelllious**
Addressing #258 in this pull request.

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
Hello,
Thank you for taking the time to contribute.
- Prajwal

I will push more changes to this, one of the main ones using curl instead of wget since curl is already required by the system.

**Comment by Prajwal-Koirala** [comment]
```
          if [ "${CURRENT_DISTRO_VERSION}" -ge 7 ]; then
            curl https://copr.fedorainfracloud.org/coprs/macieks/openresolv/repo/epel-7/macieks-openresolv-epel-7.repo -o /etc/yum.repos.d/macieks-openresolv-epel-7.repo
          elif [ "${CURRENT_DISTRO_VERSION}" -le  ]; then
            yum install https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/35/Everything/x86_64/os/Packages/o/openresolv-3.12.0-2.fc35.noarch.rpm -y
          fi
```

**Comment by Prajwal-Koirala** [comment]
This can be improved more.

**Comment by Prajwal-Koirala** [comment]
Hey for the firewall, it seems nftables will be enough on redhat based os.

**Comment by Rebelllious** [comment]
Feel free to adjust/redo whatever you want. The code I submitted does work on Fedora Server / CentOS 7 / Rocky / Alma (got a RHEL 8 VM, too, but forgot to test there). The reason I have not used nftables is that i have not touched that ever, so firewalld rules are easier for me.

**Comment by Prajwal-Koirala** [comment]
> Feel free to adjust/redo whatever you want. The code I submitted does work on Fedora Server / CentOS 7 / Rocky / Alma (got a RHEL 8 VM, too, but forgot to test there). The reason I have not used nftables is that i have not touched that ever, so firewalld rules are easier for me.

yes they are simpler but the problem with that is its bloated and outdated and i want to update to something small compared to firewalld and faster.

**Comment by Prajwal-Koirala** [comment]
Hey @Rebelllious
Just saw your email, if u have any other suggestions please create a PR or a issue.
- prajwal

**Comment by Rebelllious** [comment]
Sorry, I am Ukrainian and in the view of the latest 72 hour developments in Ukraine I don't seem to be able to attend this for quite some time. Will do later on.

**Comment by Prajwal-Koirala** [comment]
> 

Sorry to hear that dude, make sure you have the content blocker list in your blockers, I added a couple of Russia phishing domains in the last couple of days so if should help with something.

https://raw.githubusercontent.com/complexorganizations/content-blocker/main/assets/hosts

**Comment by Prajwal-Koirala** [comment]
This has been merged from a different PR.

**Pull request closed without merging**
