### PR TITLE
Dynamic apply new peer, without restart service: wg addconf. See man wg.

### PR DESCRIPTION
**Pull request by iqdoctor**

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
There is a better way to implement this, Can i change ur commit a bit?

**Comment by Prajwal-Koirala** [comment]
Hey, I remember now why it was designed like this, it was cause of the peer name.

Using the `wg` commands we cant add a name, and we need to name the peers so we can remove them later if needed.

**Comment by Prajwal-Koirala** [comment]
Can i change the code a bit?

**Comment by iqdoctor** [comment]
> Can i change the code a bit?

shure. your code - your rules. i will check changes later.

**Comment by Prajwal-Koirala** [comment]
> > Can i change the code a bit?
> 
> shure. your code - your rules. i will check changes later.

This is under public domain, i see what your trying to do and i see why people would want this but in the implementation there are a bunch of bugs that can occur.

**Comment by iqdoctor** [comment]
> Hey, I remember now why it was designed like this, it was cause of the peer name.
> Using the wg commands we cant add a name, and we need to name the peers so we can remove them later if needed.

Hey, hey.
In my variant there is bosses of both:
- I add names to all files - check /etc/wireguard/wg0.conf structure it the same
- New peers add of fly - without restart server and reinit all session

please carefully study the proposed pull request

All info written to $WIREGUARD_ADDCONF_CONFIG after successful uppend via wg addconf and then added  to $WIREGUARD_CONFIG file as in original variant!

cat $WIREGUARD_ADDCONF_CONFIG >> $WIREGUARD_CONFIG

**Comment by Prajwal-Koirala** [comment]
yes, i see that but if we do a loop of adding lets say 100 clients than the bug occurs.

**Comment by Prajwal-Koirala** [comment]
@iqdoctor
Thank you for your commit it was merged with main, the problem was that if a user added 10 peers at a time than it was going to break but deleting that file once pushing the code to `wg0` seems to do the trick.

**Pull request merged**
