### PR TITLE
[Community feedback needed]

### PR DESCRIPTION
**Pull request by Prajwal-Koirala**
The question is very simple, should i merge this simple change?

### CODE REVIEW

**Comment by Fastidious** [comment]
Your `wireguard-manager` script started as a simple way to setup a Wireguard server, and manage clients access. It has since mutated to something that is no longer just a `wireguard-manager`, with features that some--me included--may not care about, and that go way beyond managing Wireguard. I am no longer using this script.

It is your project; only you can set its course. If these changes are what you had envisioned for it, the question needed no asking, and the answer is simple: yes.

**Comment by Prajwal-Koirala** [comment]
> Your `wireguard-manager` script started as a simple way to setup a Wireguard server, and manage clients access. It has since mutated to something that is no longer just a `wireguard-manager`, with features that some--me included--may not care about, and that go way beyond managing Wireguard. I am no longer using this script.
> 
> It is your project; only you can set its course. If these changes are what you had envisioned for it, the question needed no asking, and the answer is simple: yes.

People really despise the content blocker; nevertheless, everything is optional, and you can fork the project and delete the bits you dislike.

Also, there is no vision; if I come across anything that could be beneficial to the community, it will be included or deleted; at the end of the day, this project will just be about wireguard; I will not include third-party apps.

Last but not least, the code is completely open source; fork it, change it, and do anything you want with it; I will not enforce copyright, and I will not worry about credits.

**Comment by Fastidious** [comment]
Please, I think you misunderstood my reply. I was/am not complaining, I simply provided feedback. If I took the long route, and caused a misunderstanding, I apologise. My answer would have been the same. Yes, the changes look like a good addition.

**Comment by Prajwal-Koirala** [comment]
Note: The content blocker is currently banning around 10,000 active domains that are used as malware command and control servers, so if you have malware on your system and use wireguard manager with content blocker, the malware will be unable to connect to the host.

**Comment by Saugjunkie** [comment]
The Wireguard Manager has evolved from a simple installation and management script to something more.
At the beginning there was the possibility of installing pihole, via the unbound manager, to the content blocker.

The content blocker does almost the same as the pihole but with a much better performance and the fact that it took 30 days and countless attempts should also pay much more attention to it in the Wireguard Manager.

It must be made clearer what the content blocker is intended for and how it works, as well as the usability.

With the Wireguard Manager and the Content-Blocker, development goes hand in hand and in addition to performance, it is also his strength that both come from one developer.

I think you did a good job with the idea and the implementation and everyone who understands what the content blocker does and what it is used for will love it.
It not only ensures that the annoying advertising in the apps disappears, no and that is very important to me, it makes it a lot safer for children to use.

What other solution prevents children from seeing adult advertisements when they play games from the google playstore? I don't know any and it also requires very few resources.

**Pull request merged**
