### PR TITLE
kernel

### PR DESCRIPTION
**Pull request by Prajwal-Koirala**

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
```
#!/bin/bash
version_above_4(){
    # check if $BASH_VERSION is set at all
    [ -z $BASH_VERSION ] && return 1

    # If it's set, check the version
    case $BASH_VERSION in 
        4.*) return 0 ;;
        ?) return 1;; 
    esac
}

if version_above_4
then
    echo "Good"
else
    echo "No good"
fi
```

**Comment by Prajwal-Koirala** [comment]
```
# Detect kernel version
function kernel-version() {
  if ! [ -x "$(command -v uname -r)" ]; then
    uname -r
    exit
  fi
}

# Check kernel version
kernel-version
```

**Comment by Prajwal-Koirala** [comment]
```
#!/bin/bash

version_over_4_1(){
    return $(uname -r | awk -F '.' '{
        if ($1 < 4) { print 1; }
        else if ($1 == 4) {
            if ($2 <= 1) { print 1; }
            else { print 0; }
        }
        else { print 0; }
    }')
}

if version_over_4_1
then
    echo "Kernel > 4.1"
else
    echo "Kernel <= 4.1"
fi
```

**Comment by Prajwal-Koirala** [comment]
@i077

I need help with this.

**Comment by Prajwal-Koirala** [comment]
```
#!/bin/bash

version_over_4_1(){
    return $(uname -r | awk -F '.' '{
        if ($1 < 4) { print 1; }
        else if ($1 == 4) {
            if ($2 <= 1) { print 1; }
            else { print 0; }
        }
        else { print 0; }
    }')
}

if version_over_4_1
then
    echo "Kernel > 4.1"
else
    echo "Kernel <= 4.1"
fi
```

**Comment by i077** [comment]
What exactly do you need help with? The function should do what you need, and is fairly easy to read through (just a chain of conditionals).

**Comment by Prajwal-Koirala** [comment]
> What exactly do you need help with? The function should do what you need, and is fairly easy to read through (just a chain of conditionals).

is there anyway u can rewrite it in something like this??

```
function virt-check() {
  if [ "$(systemd-detect-virt)" == "openvz" ]; then
    echo "OpenVZ virtualization is not supported (yet)."
    exit
  fi
}
```

something simple and easy to understand that anyone who would be reading would understand it??

**Comment by i077** [comment]
Hmm, given that the version is dot-separated, any one-liner in bash would definitely be harder to read. The syntax in awk is very C-like, so anyone with minimal programming experience should be able to follow what's happening.

**Pull request closed without merging**
