### PR TITLE
Credit @Rebelllious

### PR DESCRIPTION
**Pull request by Prajwal-Koirala**
Pipeline should be able to test the code and report back.

### CODE REVIEW

**Review by Rebelllious — COMMENTED** [review]
this commit breaks things in Ubuntu, for instance, where cron is used, unlike crond in the RHEL family.
I would suggest reverting it and getting my one from #272

**Comment by Prajwal-Koirala** [comment]
> this commit breaks things in Ubuntu, for instance, where cron is used, unlike crond in the RHEL family. I would suggest reverting it and getting my one from #272 - [761768c](https://github.com/complexorganizations/wireguard-manager/commit/761768cb2c525c47fc7200a6b381c8d096f23449)

This is a test commit, I am building a workflow on digital ocean so if there is a pr it will deploy all the vms and than test the code

**Comment by Prajwal-Koirala** [comment]
> this commit breaks things in Ubuntu, for instance, where cron is used, unlike crond in the RHEL family. I would suggest reverting it and getting my one from #272 - [761768c](https://github.com/complexorganizations/wireguard-manager/commit/761768cb2c525c47fc7200a6b381c8d096f23449)

Do u know any good ways to check if the system is using systemctl or service?

The code needs to be very simple and easy to understand.

**Comment by Rebelllious** [comment]
I am not really sure about other distros, but I can tell for sure that in the RHEL family we have redirection of "service service_name action" to "systemctl action service_name". Which kind of makes it not really necessary to use systemctl if you seek code unification.
Here is a test output of the crond status commands for both variants in a Rocky Linux instance:
```
[root@wireguard-test-rocky ~]# systemctl status crond
● crond.service - Command Scheduler
   Loaded: loaded (/usr/lib/systemd/system/crond.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2022-01-22 17:35:15 CET; 3 weeks 1 days ago
 Main PID: 1057 (crond)
    Tasks: 1 (limit: 11396)
   Memory: 1.5M
   CGroup: /system.slice/crond.service
           └─1057 /usr/sbin/crond -n

Feb 14 03:40:01 wireguard-test-rocky.home anacron[29577]: Normal exit (1 job run)
Feb 14 04:01:01 wireguard-test-rocky.home CROND[29626]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 05:01:01 wireguard-test-rocky.home CROND[29645]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 06:01:01 wireguard-test-rocky.home CROND[29667]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 07:01:01 wireguard-test-rocky.home CROND[29705]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 08:01:01 wireguard-test-rocky.home CROND[29726]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 09:01:01 wireguard-test-rocky.home CROND[29745]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 10:01:01 wireguard-test-rocky.home CROND[29766]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 11:01:01 wireguard-test-rocky.home CROND[29784]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 12:01:01 wireguard-test-rocky.home CROND[29819]: (root) CMD (run-parts /etc/cron.hourly)
```
and
```
[root@wireguard-test-rocky ~]# service crond status
Redirecting to /bin/systemctl status crond.service
● crond.service - Command Scheduler
   Loaded: loaded (/usr/lib/systemd/system/crond.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2022-01-22 17:35:15 CET; 3 weeks 1 days ago
 Main PID: 1057 (crond)
    Tasks: 1 (limit: 11396)
   Memory: 1.5M
   CGroup: /system.slice/crond.service
           └─1057 /usr/sbin/crond -n

Feb 14 03:40:01 wireguard-test-rocky.home anacron[29577]: Normal exit (1 job run)
Feb 14 04:01:01 wireguard-test-rocky.home CROND[29626]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 05:01:01 wireguard-test-rocky.home CROND[29645]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 06:01:01 wireguard-test-rocky.home CROND[29667]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 07:01:01 wireguard-test-rocky.home CROND[29705]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 08:01:01 wireguard-test-rocky.home CROND[29726]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 09:01:01 wireguard-test-rocky.home CROND[29745]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 10:01:01 wireguard-test-rocky.home CROND[29766]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 11:01:01 wireguard-test-rocky.home CROND[29784]: (root) CMD (run-parts /etc/cron.hourly)
Feb 14 12:01:01 wireguard-test-rocky.home CROND[29819]: (root) CMD (run-parts /etc/cron.hourly)
```
I've confirmed the same in CentOS 7 and Fedora 35 (Server), RHEL 8, Alma Linux, Oracle Linux 7 and 8 -  just to be sure.

**Pull request closed without merging**
